import './styles/main.scss'
import 'bootstrap/dist/js/bootstrap.min.js'
import './src/components/rt-dashboard/rt-dashboard'
import './src/components/dashboard/dashboard'
import './src/components/history'
import './src/components/queues/queues'
import './src/components/workers/workers'
