openapi: "3.0.0"
info:
  title: RT Dashboard API
  version: 1.0.0

paths:
  /history.json:
    get:
      summary: List history entries
      responses:
        200:
          description: |
            Return object containting list of rows and groups of history entries
          content:
            application/json:
              schema:
                type: object
                properties:
                  rows:
                    type: array
                    items:
                      type: object
                      required:
                        - group
                        - subgroup
                        - start
                        - title
                        - type
                        - content
                      properties:
                        group:
                          type: string
                          description: Name of the task
                        subgroup:
                          type: integer
                          description: Id of the worker
                        start:
                          type: integer
                          format: timestamp
                          description: Start time of the task in unix timestamp format
                        end:
                          type: integer
                          format: timestamp
                          description: End time of the task in unix timestamp format when `type` is range
                        type:
                          type: string
                          enum: [range, point]
                        content:
                          type: string
                          description: Short info about the task
                        title:
                          type: string
                          format: html
                          description: Detailed information about the task
                        style:
                          type: string
                          description: Style attribute to apply on the rendered task
                  groups:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        content:
                          type: integer
                        order:
                          type: integer
  /job/{job_id}/cancel:
    post:
      summary: Cancel the job with the specified job_id
      parameters:
        - name: job_id
          in: path
          schema:
            type: string
            format: uuid
          required: true
      responses:
        200:
          description: Request processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /queue/{queue_name}/empty:
    post:
      summary: Empty the queue with the specified queue_name
      parameters:
        - name: queue_name
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          description: Request processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /queue/{queue_name}/delete:
    post:
      summary: Delete the queue with the specified queue_name
      parameters:
        - name: queue_name
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          description: Request processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /queues.json:
    get:
      summary: List Queues and their state
      responses:
        200:
          description: |
            Return object containing a list of queues and the `[failed]`,
            `[finished]` and `[running]` registries, the number of elements
            in them and an url for more details on them.
          content:
            application/json:
              schema:
                type: object
                required:
                  - queues
                properties:
                  queues:
                    type: array
                    items:
                      type: object
                      required:
                        - name
                        - count
                        - url
                      properties:
                        name:
                          type: string
                        count:
                          type: integer
                        url:
                          type: string
                          format: url
  /jobs/{queue_name}/{page}.json:
    get:
      summary: List workers and their state
      parameters:
        - name: queue_name
          in: path
          schema:
            type: string
          required: true
        - name: page
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: |
            Return object containting list of worker states in workers property
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  jobs:
                    type: array
                    description: |
                      Default ordering is oldest entries first, except for the
                      `[failed]` and `[finished]` registries, where it is newest first.
                    items:
                      type: object
                      required: 
                        - id
                        - status
                        - enqueued_at
                        - started_at
                        - ended_at
                        - origin
                        - error_message
                        - description
                      properties:
                        id:
                          type: string
                          format: uuid
                        status:
                          type: string
                        enqueued_at:
                          type: string
                          format: date-time
                        started_at:
                          type: string
                          format: date-time
                        ended_at:
                          type: string
                          format: date-time
                        origin:
                          type: string
                        error_message:
                          type: string
                        description:
                          type: string
                        worker:
                          type: string
                          description: |
                            Description of Worker that the job is being executed on.
                            Only present for running jobs (aka in `[running]` registry)
                  pagination:
                    type: object
                    properties:
                      pages_in_window:
                        type: array
                        items:
                          type: object
                          properties:
                            number:
                              type: integer
                            url:
                              type: string
                              format: url
                      next_page:
                        type: object
                        nullable: true
                        description: |
                          Despite the naming actually provides a link to the LAST page.
                          On the last page 'null' is used instead of an object.
                        properties:
                          url:
                            type: string
                            format: url
                      prev_page:
                        type: object
                        nullable: true
                        description: |
                          Despite the naming actually provides a link to the FIRST page.
                          On the first page 'null' is used instead of an object.
                        properties:
                          url:
                            type: string
                            format: url
  /workers.json:
    get:
      summary: List workers and their state
      responses:
        200:
          description: |
            Return object containting list of worker states in workers property
          content:
            application/json:
              schema:
                type: object
                properties:
                  workers:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        queues:
                          type: array
                          items:
                            type: string
                        state:
                          type: string
