openapi: "3.0.0"
info:
  title: RT Dashboard API
  version: 1.0.0

paths:
#  /:
#  /{queue_name}:
#  /{queue_name}/{page}:
#  /history:
#  /queues.json:
  /queue/{queue_name}/delete:
    post:
      summary: Cancel the job with the specified job_id
      parameters:
        - name: queue_name
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          description: Request processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /workers.json:
    get:
      summary: List workers and their state
      responses:
        200:
          description: |
            Return object containting list of worker states in workers property 
          content:
            application/json:
              schema:
                type: object
                properties:
                  workers:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        queues:
                          type: array
                          items:
                            type: string
                        state:
                          type: string
                

#  /jobs/{queue_name}/{page}.json:
  /job/{job_id}/cancel:
    post:
      summary: Cancel the job with the specified job_id
      parameters:
        - name: job_id
          in: path
          schema:
            type: string
            format: uuid
          required: true
      responses:
        200:
          description: Request processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
#  /history.json:
